services:
  grafana:
    image: grafana/grafana-oss
    container_name: grafana
    restart: unless-stopped
    environment:
      # Environment variables with defaults/fallbacks
      - GF_SERVER_DOMAIN=${GRAFANA_DOMAIN:-}
      - GF_SERVER_ROOT_URL=${GRAFANA_URL:-}
      - GF_SECURITY_ADMIN_PASSWORD=${GRAFANA_PASSWORD:-admin} # admin/admin is default Grafana login. Set $GRAFANA_PASSWORD in production!
      # Environment variables with fixed values
      - GF_AUTH_ANONYMOUS_ENABLED=true
      - GF_PATHS_CONFIG=/etc/grafana/custom.ini
      - GF_PLUGINS_PREINSTALL=iosb-sensorthings-datasource,felixrelleum-geomapwms-panel,yesoreyeram-infinity-datasource
    ports:
      - '3000:3000'
    volumes:
      - grafana_storage:/var/lib/grafana
      - ./custom.ini:/etc/grafana/custom.ini
      - ./provider.yaml:/etc/grafana/provisioning/dashboards/main.yaml
      - ./datasource.yaml:/etc/grafana/provisioning/datasources/main.yaml
      - ./dashboards:/var/lib/grafana/dashboards
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.grafana.rule=Host(`${GRAFANA_DOMAIN:-}`)"
      - "traefik.http.routers.grafana.entrypoints=websecure"
      - "traefik.http.routers.grafana.tls.certresolver=letsencrypt"

volumes:
  grafana_storage: {}