services:
  traefik:
    image: traefik:v3.3
    container_name: traefik
    command:
      - "--log.level=DEBUG"
      - "--api.insecure=true"
      - "--providers.docker=true"
      - "--providers.docker.exposedbydefault=false"
      - "--entryPoints.websecure.address=:443"
      - "--certificatesresolvers.letsencrypt.acme.tlschallenge=true"
      #- "--certificatesresolvers.letsencrypt.acme.caserver=https://acme-staging-v02.api.letsencrypt.org/directory"
      - "--certificatesresolvers.letsencrypt.acme.email=${TLS_EMAIL}"
      - "--certificatesresolvers.letsencrypt.acme.storage=/letsencrypt/acme.json"
    ports:
      - "443:443"
    volumes:
      - "./letsencrypt:/letsencrypt"
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
    labels:
      # Proxy to RIVM samen meten API. Not used by Grafana but used for the sensordata-web-ui.
      - "traefik.http.routers.external-proxy.rule=Host(`sensordata-dashboard.mindloops.io`) && PathPrefix(`/rivm-proxy`)"
      - "traefik.http.routers.external-proxy.entrypoints=websecure"
      - "traefik.http.routers.external-proxy.tls.certresolver=letsencrypt"
      - "traefik.http.routers.external-proxy.service=external-service"
      - "traefik.http.routers.external-proxy.middlewares=cors-headers"

      # Service to external URL
      - "traefik.http.services.external-service.loadbalancer.server.url=https://api-samenmeten.rivm.nl"

      # CORS Middleware
      - "traefik.http.middlewares.cors-headers.headers.accesscontrolallowmethods=GET,HEAD,OPTIONS"
      - "traefik.http.middlewares.cors-headers.headers.accesscontrolallowheaders=*"
      - "traefik.http.middlewares.cors-headers.headers.accesscontrolalloworiginlist=*"
      - "traefik.http.middlewares.cors-headers.headers.accesscontrolallowcredentials=true"
      - "traefik.http.middlewares.cors-headers.headers.addvaryheader=true"
