services:
  grafana:
    image: grafana/grafana-enterprise
    container_name: grafana
    restart: unless-stopped
    environment:
      #- GF_SERVER_ROOT_URL=http://my.grafana.server/
      - GF_PLUGINS_PREINSTALL=iosb-sensorthings-datasource
    ports:
      - '3000:3000'
    volumes:
      - grafana_storage:/var/lib/grafana
      - ./provider.yaml:/etc/grafana/provisioning/dashboards/main.yaml
      - ./datasource.yaml:/etc/grafana/provisioning/datasources/main.yaml
      - ./dashboards:/var/lib/grafana/dashboards
volumes:
  grafana_storage: {}