name: Deploy

on:
  push:
    branches: [ "master" ]
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Deploy to Remote Server
      run: |
        sshpass -p "${{ secrets.SSH_PASSWORD }}" ssh -o StrictHostKeyChecking=no -p "${{ secrets.SSH_PORT }}" "${{ secrets.SSH_USERNAME }}@${{ secrets.SSH_HOST }}" << EOF
          mkdir -p "dashboard" && cd "dashboard"
        
          # Clone or update
          [ ! -d .git ] && git clone https://github.com/mindloops/sensordata-dashboard . || git fetch --all && git reset --hard origin/master
                  
          # Stop Grafana (clean sheet)
          docker compose down -v
        
          # Start Grafana
          TLS_EMAIL="${{ secrets.TLS_EMAIL }}" GRAFANA_DOMAIN="${{ secrets.GRAFANA_DOMAIN }}" GRAFANA_PASSWORD="${{ secrets.GRAFANA_PASSWORD }}" docker compose -f docker-compose.yaml -f docker-compose.https.yaml up -d
        EOF
