name: Deploy

on:
  # Triggers the workflow on push or pull request events but only for the "master" branch
  push:
    branches: [ "master" ]
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Deploy to Remote Server
      run: |
        sshpass -p "${{ secrets.SSH_PASSWORD }}" ssh -o StrictHostKeyChecking=no -p "${{ secrets.SSH_PORT }}" "${{ secrets.SSH_USERNAME }}@${{ secrets.SSH_HOST }}" << EOF
          mkdir -p "dashboard" && cd "dashboard"
        
          # Clone or update
          [ ! -d .git ] && git clone https://github.com/mindloops/sensordata-dashboard . || git pull
          
          # Make dashboard suitable for use on server
          sed -i "s/^admin_password = .*/admin_password = ${{ secrets.GRAFANA_PASSWORD }}/" custom.ini
        
          # Start Grafana
          docker compose pull && docker compose up -d --force-recreate
        EOF
